// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetServiceClient interface {
	SeyHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error)
	SeyHelloServiceStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (GreetService_SeyHelloServiceStreamingClient, error)
	SeyHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SeyHelloClientStreamingClient, error)
	SeyHelloBidirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SeyHelloBidirectionalStreamingClient, error)
}

type greetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiceClient(cc grpc.ClientConnInterface) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) SeyHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/greet_service.GreetService/SeyHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) SeyHelloServiceStreaming(ctx context.Context, in *NamesList, opts ...grpc.CallOption) (GreetService_SeyHelloServiceStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[0], "/greet_service.GreetService/SeyHelloServiceStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSeyHelloServiceStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_SeyHelloServiceStreamingClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServiceSeyHelloServiceStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceSeyHelloServiceStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SeyHelloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SeyHelloClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[1], "/greet_service.GreetService/SeyHelloClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSeyHelloClientStreamingClient{stream}
	return x, nil
}

type GreetService_SeyHelloClientStreamingClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*MessagesList, error)
	grpc.ClientStream
}

type greetServiceSeyHelloClientStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceSeyHelloClientStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceSeyHelloClientStreamingClient) CloseAndRecv() (*MessagesList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessagesList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SeyHelloBidirectionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SeyHelloBidirectionalStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[2], "/greet_service.GreetService/SeyHelloBidirectionalStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSeyHelloBidirectionalStreamingClient{stream}
	return x, nil
}

type GreetService_SeyHelloBidirectionalStreamingClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServiceSeyHelloBidirectionalStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceSeyHelloBidirectionalStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceSeyHelloBidirectionalStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
// All implementations must embed UnimplementedGreetServiceServer
// for forward compatibility
type GreetServiceServer interface {
	SeyHello(context.Context, *NoParam) (*HelloResponse, error)
	SeyHelloServiceStreaming(*NamesList, GreetService_SeyHelloServiceStreamingServer) error
	SeyHelloClientStreaming(GreetService_SeyHelloClientStreamingServer) error
	SeyHelloBidirectionalStreaming(GreetService_SeyHelloBidirectionalStreamingServer) error
	mustEmbedUnimplementedGreetServiceServer()
}

// UnimplementedGreetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (UnimplementedGreetServiceServer) SeyHello(context.Context, *NoParam) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeyHello not implemented")
}
func (UnimplementedGreetServiceServer) SeyHelloServiceStreaming(*NamesList, GreetService_SeyHelloServiceStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SeyHelloServiceStreaming not implemented")
}
func (UnimplementedGreetServiceServer) SeyHelloClientStreaming(GreetService_SeyHelloClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SeyHelloClientStreaming not implemented")
}
func (UnimplementedGreetServiceServer) SeyHelloBidirectionalStreaming(GreetService_SeyHelloBidirectionalStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SeyHelloBidirectionalStreaming not implemented")
}
func (UnimplementedGreetServiceServer) mustEmbedUnimplementedGreetServiceServer() {}

// UnsafeGreetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServiceServer will
// result in compilation errors.
type UnsafeGreetServiceServer interface {
	mustEmbedUnimplementedGreetServiceServer()
}

func RegisterGreetServiceServer(s grpc.ServiceRegistrar, srv GreetServiceServer) {
	s.RegisterService(&GreetService_ServiceDesc, srv)
}

func _GreetService_SeyHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).SeyHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet_service.GreetService/SeyHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).SeyHello(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_SeyHelloServiceStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NamesList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).SeyHelloServiceStreaming(m, &greetServiceSeyHelloServiceStreamingServer{stream})
}

type GreetService_SeyHelloServiceStreamingServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greetServiceSeyHelloServiceStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceSeyHelloServiceStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_SeyHelloClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).SeyHelloClientStreaming(&greetServiceSeyHelloClientStreamingServer{stream})
}

type GreetService_SeyHelloClientStreamingServer interface {
	SendAndClose(*MessagesList) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServiceSeyHelloClientStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceSeyHelloClientStreamingServer) SendAndClose(m *MessagesList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceSeyHelloClientStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_SeyHelloBidirectionalStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).SeyHelloBidirectionalStreaming(&greetServiceSeyHelloBidirectionalStreamingServer{stream})
}

type GreetService_SeyHelloBidirectionalStreamingServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServiceSeyHelloBidirectionalStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceSeyHelloBidirectionalStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceSeyHelloBidirectionalStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetService_ServiceDesc is the grpc.ServiceDesc for GreetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SeyHello",
			Handler:    _GreetService_SeyHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SeyHelloServiceStreaming",
			Handler:       _GreetService_SeyHelloServiceStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SeyHelloClientStreaming",
			Handler:       _GreetService_SeyHelloClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SeyHelloBidirectionalStreaming",
			Handler:       _GreetService_SeyHelloBidirectionalStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
